version: "3"
services:
  db:
    image: registry.redhat.io/rhel8/mariadb-103
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 60s
      retries: 10
    volumes:
      - mariadb:/var/lib/mysql/data
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME:-beaker}
      - MYSQL_USER=${DATABASE_USER:-beaker}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:-beaker}
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_CHARSET=utf8
  beaker-server:
    build: ./beaker-server
    depends_on:
      - db
    ports:
      - "8080:80"
  beaker-lab-controller:
    build: ./beaker-lab-controller
    depends_on:
      - beaker-server
    volumes:
      - ./beaker-lab-controller/tftpboot:/var/lib/tftpboot
#  dnsmasq:
#    build: ./dnsmasq
#    volumes:
#      - ./dnsmasq/beaker.conf:/etc/dnsmasq.d/beaker.conf
volumes:
  mariadb:
