version: "3"
services:
  db:
    image: registry.redhat.io/rhel8/mariadb-103
    volumes:
      - mariadb:/var/lib/mysql/data
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME:-beaker}
      - MYSQL_USER=${DATABASE_USER:-beaker}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:-beaker}
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_CHARSET=utf8
    ports:
      - "3306:3306"
  beaker_server:
    build: ./beaker_server
    #DB should be up/configured before beaker_server
    depends_on: 
      - db
    volumes:
      - ./beaker_server/beaker_cfg/server.cfg:/etc/beaker/server.cfg
      - ./beaker_server/beaker_cfg/client.conf:/etc/beaker/client.conf
      - /var/www/html:/var/www/html
    ports:
      - "8080:80"
  beaker_lab_controller:
    #Start after server to register power scripts with server?
    depends_on: 
      - beaker_server
    build: ./beaker_lab_controller
    volumes:
      - ./beaker_lab_controller/cfg/labcontroller.conf:/etc/beaker/labcontroller.conf
      - ./beaker_lab_controller/cfg/tftp/tftp:/etc/xinetd.d/tftp
      - ./beaker_lab_controller/files/ipmitool_lanplus:/etc/beaker/power-scripts/ipmitool_lanplus
      - ./beaker_lab_controller/files/redfish:/etc/beaker/power-scripts/redfish
      - ./beaker_lab_controller/tftpboot:/var/lib/tftpboot
#  dnsmasq:
#TODO
#    image:
#    volumes
