---
- name: Setup Beaker
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: "Setup beaker"
      include_role:
        name: setup_beaker

    - name: Open port in firewall for DNS
      firewalld:
        port: "53/udp"
        permanent: yes
        immediate: yes
        state: enabled
        zone: "{{ item }}"
      loop:
        - internal
        - public
